development: &development
  adapter: postgresql
  encoding: unicode
  database: ranktrail_dev
  pool: 5
  username: gritinnovation
  password: gritinnovation
  host: localhost

staging: &staging
  adapter: postgresql
  encoding: unicode
  database: rank_tracker_app_development
  pool: 5
  username: gritinnovation
  password: gritinnovation
  host: localhost

# development:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: online_sep22-1_development #change database name as you want
#   pool: 5
#   username: root   #user name while you created mysql installation
#   password:   #password which you have given during mysql installation
#   host: localhost

# test:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: online_sep22-1_test
#   pool: 5
#   username: root
#   password: 
#   host: localhost

# production:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: online_sep22-1_production
#   pool: 5
#   username: root
#   password: 
#   host: localhost

#==================
# if you use sqllite then use this 

default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development_seedpod3.sqlite3

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: db/test_seedpod3.sqlite3

production:
  <<: *default
  database: db/production.sqlite3


